## Case When formatting test

### Goals

Answer question from `orbital` team: 

> Does "unnesting" queries improve performance for trees? If only sometimes, where/when?

Research design:

- Simulate SQL code for medium-size random forest:
  + Max Depth: 4 (2**4 terminal nodes)
  + Trees: 100
- Test three different varieties for performance:
  + Original nested CASE WHEN
  + "Linearized" CASE WHEN (pulling all conditions to top level)
  + "Smart" Linearized -- same as above but with refundant conditions removed
- Test on two different data distributions:
  + Uniformly distributed (all nodes have same chance of terminating)
  + Skewed distribution (to simulate if we re-rodered query to take advantage of CASE WHEN early term)

### Set Up -- Tree Code

In [1]:
import duckdb
import polars as pl
import polars.selectors as cs
import sqlglot
import pandas as pd
import numpy as np

In [2]:
# nested case when version
d = []
for i in np.arange(8):
    d += [ f"case when d{i+1} > 0.5 then {i+1} else 0 end"]

c = []
for i in np.arange(4):
    sql_temp = f"case when c{i+1} > 0.5 then {d[2*i]} else {d[2*i+1]} end"
    c += [sql_temp]

b = []
for i in np.arange(2):
    sql_temp = f"case when b{i+1} > 0.5 then {c[2*i]} else {c[2*i+1]} end"
    b += [sql_temp]

sql_nest = f"case when a > 0.5 then {b[0]} else {b[1]} end"

print(
    sqlglot.transpile(sql_nest, write="duckdb", identify=True, pretty=True)[0]
)

CASE
  WHEN "a" > 0.5
  THEN CASE
    WHEN "b1" > 0.5
    THEN CASE
      WHEN "c1" > 0.5
      THEN CASE WHEN "d1" > 0.5 THEN 1 ELSE 0 END
      ELSE CASE WHEN "d2" > 0.5 THEN 2 ELSE 0 END
    END
    ELSE CASE
      WHEN "c2" > 0.5
      THEN CASE WHEN "d3" > 0.5 THEN 3 ELSE 0 END
      ELSE CASE WHEN "d4" > 0.5 THEN 4 ELSE 0 END
    END
  END
  ELSE CASE
    WHEN "b2" > 0.5
    THEN CASE
      WHEN "c3" > 0.5
      THEN CASE WHEN "d5" > 0.5 THEN 5 ELSE 0 END
      ELSE CASE WHEN "d6" > 0.5 THEN 6 ELSE 0 END
    END
    ELSE CASE
      WHEN "c4" > 0.5
      THEN CASE WHEN "d7" > 0.5 THEN 7 ELSE 0 END
      ELSE CASE WHEN "d8" > 0.5 THEN 8 ELSE 0 END
    END
  END
END
CASE
  WHEN "a" > 0.5
  THEN CASE
    WHEN "b1" > 0.5
    THEN CASE
      WHEN "c1" > 0.5
      THEN CASE WHEN "d1" > 0.5 THEN 1 ELSE 0 END
      ELSE CASE WHEN "d2" > 0.5 THEN 2 ELSE 0 END
    END
    ELSE CASE
      WHEN "c2" > 0.5
      THEN CASE WHEN "d3" > 0.5 THEN 3 ELSE 0 END
      ELSE CASE WHEN "d4" > 0.5 THEN 4 ELSE 0 END
    END
  END
  ELSE CASE
    WHEN "b2" > 0.5
    THEN CASE
      WHEN "c3" > 0.5
      THEN CASE WHEN "d5" > 0.5 THEN 5 ELSE 0 END
      ELSE CASE WHEN "d6" > 0.5 THEN 6 ELSE 0 END
    END
    ELSE CASE
      WHEN "c4" > 0.5
      THEN CASE WHEN "d7" > 0.5 THEN 7 ELSE 0 END
      ELSE CASE WHEN "d8" > 0.5 THEN 8 ELSE 0 END
    END
  END
END

In [3]:
# linearize case when version 
# using strict versus equalities versus inclusion / exclusion just so my code lines up nice =) 
# it's a timing exercise so it really doesn't matter
sql_line = '''
case
-- a > 0.5
when a > 0.5 and b1 > 0.5 and c1 > 0.5 and d1 > 0.5 then 1
when a > 0.5 and b1 > 0.5 and c1 > 0.5 and d1 < 0.5 then 0 
when a > 0.5 and b1 > 0.5 and c1 < 0.5 and d2 > 0.5 then 2
when a > 0.5 and b1 > 0.5 and c1 < 0.5 and d2 < 0.5 then 0
when a > 0.5 and b1 < 0.5 and c2 > 0.5 and d3 > 0.5 then 3
when a > 0.5 and b1 < 0.5 and c2 > 0.5 and d3 < 0.5 then 0 
when a > 0.5 and b1 < 0.5 and c2 < 0.5 and d4 > 0.5 then 4
when a > 0.5 and b1 < 0.5 and c2 < 0.5 and d4 < 0.5 then 0
-- a <= 0.5
when a < 0.5 and b2 > 0.5 and c3 > 0.5 and d5 > 0.5 then 5
when a < 0.5 and b2 > 0.5 and c3 > 0.5 and d5 < 0.5 then 0 
when a < 0.5 and b2 > 0.5 and c3 < 0.5 and d6 > 0.5 then 6
when a < 0.5 and b2 > 0.5 and c3 < 0.5 and d6 < 0.5 then 0
when a < 0.5 and b2 < 0.5 and c4 > 0.5 and d7 > 0.5 then 7
when a < 0.5 and b2 < 0.5 and c4 > 0.5 and d7 < 0.5 then 0 
when a < 0.5 and b2 < 0.5 and c4 < 0.5 and d8 > 0.5 then 8
when a < 0.5 and b2 < 0.5 and c4 < 0.5 and d8 < 0.5 then 0
else null end
'''

print(
    sqlglot.transpile(sql_line, write="duckdb", identify=True, pretty=True)[0]
)

CASE
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5 AND "d1" > 0.5
  THEN 1
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5 AND "d1" < 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" < 0.5 AND "d2" > 0.5
  THEN 2
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" < 0.5 AND "d2" < 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" > 0.5 AND "d3" > 0.5
  THEN 3
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" > 0.5 AND "d3" < 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" < 0.5 AND "d4" > 0.5
  THEN 4
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" < 0.5 AND "d4" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" > 0.5 AND "d5" > 0.5
  THEN 5
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" > 0.5 AND "d5" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" < 0.5 AND "d6" > 0.5
  THEN 6
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" < 0.5 AND "d6" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" > 0.5 AND "d7" > 0.5
  THEN 7
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" > 0.5 AND "d7" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" < 0.5 AND "d8" > 0.5
  THEN 8
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" < 0.5 AND "d8" < 0.5
  THEN 0
  ELSE NULL
END
CASE
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5 AND "d1" > 0.5
  THEN 1
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5 AND "d1" < 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" < 0.5 AND "d2" > 0.5
  THEN 2
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" < 0.5 AND "d2" < 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" > 0.5 AND "d3" > 0.5
  THEN 3
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" > 0.5 AND "d3" < 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" < 0.5 AND "d4" > 0.5
  THEN 4
  WHEN "a" > 0.5 AND "b1" < 0.5 AND "c2" < 0.5 AND "d4" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" > 0.5 AND "d5" > 0.5
  THEN 5
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" > 0.5 AND "d5" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" < 0.5 AND "d6" > 0.5
  THEN 6
  WHEN "a" < 0.5 AND "b2" > 0.5 AND "c3" < 0.5 AND "d6" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" > 0.5 AND "d7" > 0.5
  THEN 7
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" > 0.5 AND "d7" < 0.5
  THEN 0
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" < 0.5 AND "d8" > 0.5
  THEN 8
  WHEN "a" < 0.5 AND "b2" < 0.5 AND "c4" < 0.5 AND "d8" < 0.5
  THEN 0
  ELSE NULL
END

In [4]:
# linearized case when version -- pruning redundant conditions
sql_slim = '''
case
-- a > 0.5
when a > 0.5 and b1 > 0.5 and c1 > 0.5 and d1 > 0.5 then 1
when a > 0.5 and b1 > 0.5 and c1 > 0.5              then 0 
when a > 0.5 and b1 > 0.5              and d2 > 0.5 then 2
when a > 0.5 and b1 > 0.5                           then 0
when a > 0.5 and              c2 > 0.5 and d3 > 0.5 then 3
when a > 0.5 and              c2 > 0.5              then 0 
when a > 0.5 and                           d4 > 0.5 then 4
when a > 0.5                                        then 0
-- a <= 0.5
when             b2 > 0.5 and c3 > 0.5 and d5 > 0.5 then 5
when             b2 > 0.5 and c3 > 0.5              then 0 
when             b2 > 0.5              and d6 > 0.5 then 6
when             b2 > 0.5                           then 0
when                          c4 > 0.5 and d7 > 0.5 then 7
when                          c4 > 0.5              then 0 
when                                       d8 > 0.5 then 8
when a < 0.5                                        then 0
else null end
'''

print(
    sqlglot.transpile(sql_slim, write="duckdb", identify=True, pretty=True)[0]
)

CASE
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5 AND "d1" > 0.5
  THEN 1
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "d2" > 0.5
  THEN 2
  WHEN "a" > 0.5 AND "b1" > 0.5
  THEN 0
  WHEN "a" > 0.5 AND "c2" > 0.5 AND "d3" > 0.5
  THEN 3
  WHEN "a" > 0.5 AND "c2" > 0.5
  THEN 0
  WHEN "a" > 0.5 AND "d4" > 0.5
  THEN 4
  WHEN "a" > 0.5
  THEN 0
  WHEN "b2" > 0.5 AND "c3" > 0.5 AND "d5" > 0.5
  THEN 5
  WHEN "b2" > 0.5 AND "c3" > 0.5
  THEN 0
  WHEN "b2" > 0.5 AND "d6" > 0.5
  THEN 6
  WHEN "b2" > 0.5
  THEN 0
  WHEN "c4" > 0.5 AND "d7" > 0.5
  THEN 7
  WHEN "c4" > 0.5
  THEN 0
  WHEN "d8" > 0.5
  THEN 8
  WHEN "a" < 0.5
  THEN 0
  ELSE NULL
END
CASE
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5 AND "d1" > 0.5
  THEN 1
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "c1" > 0.5
  THEN 0
  WHEN "a" > 0.5 AND "b1" > 0.5 AND "d2" > 0.5
  THEN 2
  WHEN "a" > 0.5 AND "b1" > 0.5
  THEN 0
  WHEN "a" > 0.5 AND "c2" > 0.5 AND "d3" > 0.5
  THEN 3
  WHEN "a" > 0.5 AND "c2" > 0.5
  THEN 0
  WHEN "a" > 0.5 AND "d4" > 0.5
  THEN 4
  WHEN "a" > 0.5
  THEN 0
  WHEN "b2" > 0.5 AND "c3" > 0.5 AND "d5" > 0.5
  THEN 5
  WHEN "b2" > 0.5 AND "c3" > 0.5
  THEN 0
  WHEN "b2" > 0.5 AND "d6" > 0.5
  THEN 6
  WHEN "b2" > 0.5
  THEN 0
  WHEN "c4" > 0.5 AND "d7" > 0.5
  THEN 7
  WHEN "c4" > 0.5
  THEN 0
  WHEN "d8" > 0.5
  THEN 8
  WHEN "a" < 0.5
  THEN 0
  ELSE NULL
END

### Set Up -- Data

In [5]:
# set up random data matrix
n = 1000000
p = 15
df = pl.DataFrame( np.random.rand(n,p) )
df.columns = ['a','b1','b2','c1','c2','c3','c4','d1','d2','d3','d4','d5','d6','d7','d8']
df.glimpse()

Rows: 1000000
Columns: 15
$ a  <f64> 0.14742862407897683, 0.24509657297465526, 0.9157016094920555, 0.46049170704702747, 0.16646005656379437, 0.4699246791623134, 0.09584973483097892, 0.17292273422153204, 0.7094978449182209, 0.9598546374895349
$ b1 <f64> 0.3858745827643171, 0.43421161692908283, 0.7202045582793047, 0.0846856930359059, 0.6886670916128049, 0.49167612297020047, 0.4155659640761824, 0.157531920691674, 0.3427860858381807, 0.7957118480893528
$ b2 <f64> 0.3164442816774753, 0.6001987158026171, 0.4112645835076493, 0.40070428002129854, 0.7151980823009808, 0.016709009126246843, 0.4166904671360554, 0.9857036022423527, 0.49329682662496055, 0.5447655925714029
$ c1 <f64> 0.6060068316712116, 0.9217608598774895, 0.33719086675413257, 0.522525256002867, 0.5260573938393311, 0.05460309179320233, 0.24268677510969883, 0.7169707516332251, 0.0349483301363418, 0.09706311781402266
$ c2 <f64> 0.9262130447105582, 0.9293303278684152, 0.6462818995845517, 0.09518633400817789, 0.30238470887198365, 0.006561311163518768, 0.06676150367832878, 0.41988324013751444, 0.26639842300572547, 0.23838072197473215
$ c3 <f64> 0.43688671265548407, 0.42278848983765493, 0.35663102601330465, 0.7120850663503406, 0.5621900729953628, 0.06496172336240402, 0.7980121084636208, 0.8236675997658558, 0.9837852146317149, 0.966452673917894
$ c4 <f64> 0.6114663528882051, 0.29146527100379727, 0.21116345539017967, 0.09438613155291853, 0.37028738894339863, 0.6919560812044973, 0.5969405028846212, 0.43681639527428107, 0.2992273857476557, 0.25043787671387285
$ d1 <f64> 0.914330903431379, 0.38659705652243714, 0.025140263271191565, 0.2260315206897906, 0.9881537013174734, 0.8881707752265534, 0.8873450930231852, 0.05629771426169117, 0.6555136356462237, 0.35845441687020874
$ d2 <f64> 0.26326385945838904, 0.800475477732445, 0.4799073636007878, 0.17041429667275676, 0.6324768010096627, 0.9379587908530118, 0.30034524408343477, 0.5875057403851488, 0.832040463857867, 0.6414378924428155
$ d3 <f64> 0.8034112880438383, 0.5636599218835489, 0.9493134700213239, 0.46461736051228186, 0.22560743695967367, 0.9113861918560662, 0.4756891274013614, 0.505247667193434, 0.529628873314988, 0.7050028361576569
$ d4 <f64> 0.8608439882678307, 0.6804682821104526, 0.3138267089710197, 0.7563354578726651, 0.5920745894270639, 0.30468411906775883, 0.3985032900407509, 0.12214707979091122, 0.7838904790911908, 0.8207213585011792
$ d5 <f64> 0.2979406188016187, 0.814930844971334, 0.5471204991927345, 0.09331215491951661, 0.6821422338261772, 0.3274588988900595, 0.45347393795472846, 0.23366489698685056, 0.8364738547424555, 0.03436511054946656
$ d6 <f64> 0.8616046773071844, 0.7764855756602473, 0.3014725963469608, 0.7019671675172522, 0.7023440181013777, 0.7097362082679255, 0.7349050265517291, 0.46366395280563755, 0.23396076203348515, 0.09027162567508829
$ d7 <f64> 0.6882800376658483, 0.3773063728510738, 0.8210445818188912, 0.8029873098958115, 0.299374704732589, 0.8021939067346116, 0.43293528084244415, 0.45114838126830925, 0.6766553477078299, 0.984045809279959
$ d8 <f64> 0.06877100285681781, 0.5158641826936722, 0.14860881830708117, 0.43163610535048547, 0.3053387174128692, 0.6319213971366198, 0.6538838787399885, 0.2573103511205207, 0.9681121218064074, 0.23681711445975684

Rows: 1000000
Columns: 15
$ a  <f64> 0.14742862407897683, 0.24509657297465526, 0.9157016094920555, 0.46049170704702747, 0.16646005656379437, 0.4699246791623134, 0.09584973483097892, 0.17292273422153204, 0.7094978449182209, 0.9598546374895349
$ b1 <f64> 0.3858745827643171, 0.43421161692908283, 0.7202045582793047, 0.0846856930359059, 0.6886670916128049, 0.49167612297020047, 0.4155659640761824, 0.157531920691674, 0.3427860858381807, 0.7957118480893528
$ b2 <f64> 0.3164442816774753, 0.6001987158026171, 0.4112645835076493, 0.40070428002129854, 0.7151980823009808, 0.016709009126246843, 0.4166904671360554, 0.9857036022423527, 0.49329682662496055, 0.5447655925714029
$ c1 <f64> 0.6060068316712116, 0.9217608598774895, 0.33719086675413257, 0.522525256002867, 0.5260573938393311, 0.05460309179320233, 0.24268677510969883, 0.7169707516332251, 0.0349483301363418, 0.09706311781402266
$ c2 <f64> 0.9262130447105582, 0.9293303278684152, 0.6462818995845517, 0.09518633400817789, 0.30238470887198365, 0.006561311163518768, 0.06676150367832878, 0.41988324013751444, 0.26639842300572547, 0.23838072197473215
$ c3 <f64> 0.43688671265548407, 0.42278848983765493, 0.35663102601330465, 0.7120850663503406, 0.5621900729953628, 0.06496172336240402, 0.7980121084636208, 0.8236675997658558, 0.9837852146317149, 0.966452673917894
$ c4 <f64> 0.6114663528882051, 0.29146527100379727, 0.21116345539017967, 0.09438613155291853, 0.37028738894339863, 0.6919560812044973, 0.5969405028846212, 0.43681639527428107, 0.2992273857476557, 0.25043787671387285
$ d1 <f64> 0.914330903431379, 0.38659705652243714, 0.025140263271191565, 0.2260315206897906, 0.9881537013174734, 0.8881707752265534, 0.8873450930231852, 0.05629771426169117, 0.6555136356462237, 0.35845441687020874
$ d2 <f64> 0.26326385945838904, 0.800475477732445, 0.4799073636007878, 0.17041429667275676, 0.6324768010096627, 0.9379587908530118, 0.30034524408343477, 0.5875057403851488, 0.832040463857867, 0.6414378924428155
$ d3 <f64> 0.8034112880438383, 0.5636599218835489, 0.9493134700213239, 0.46461736051228186, 0.22560743695967367, 0.9113861918560662, 0.4756891274013614, 0.505247667193434, 0.529628873314988, 0.7050028361576569
$ d4 <f64> 0.8608439882678307, 0.6804682821104526, 0.3138267089710197, 0.7563354578726651, 0.5920745894270639, 0.30468411906775883, 0.3985032900407509, 0.12214707979091122, 0.7838904790911908, 0.8207213585011792
$ d5 <f64> 0.2979406188016187, 0.814930844971334, 0.5471204991927345, 0.09331215491951661, 0.6821422338261772, 0.3274588988900595, 0.45347393795472846, 0.23366489698685056, 0.8364738547424555, 0.03436511054946656
$ d6 <f64> 0.8616046773071844, 0.7764855756602473, 0.3014725963469608, 0.7019671675172522, 0.7023440181013777, 0.7097362082679255, 0.7349050265517291, 0.46366395280563755, 0.23396076203348515, 0.09027162567508829
$ d7 <f64> 0.6882800376658483, 0.3773063728510738, 0.8210445818188912, 0.8029873098958115, 0.299374704732589, 0.8021939067346116, 0.43293528084244415, 0.45114838126830925, 0.6766553477078299, 0.984045809279959
$ d8 <f64> 0.06877100285681781, 0.5158641826936722, 0.14860881830708117, 0.43163610535048547, 0.3053387174128692, 0.6319213971366198, 0.6538838787399885, 0.2573103511205207, 0.9681121218064074, 0.23681711445975684

In [6]:
# ensure different candidates have same logic
sql_compare = f"""
select
{sql_nest} as out_nest,
{sql_line} as out_line,
{sql_slim} as out_slim,
*
from df
"""
df_out = duckdb.sql(sql_compare).pl()
df_out.filter( 
    (pl.col('out_line') != pl.col('out_slim')) |
    (pl.col('out_nest') != pl.col('out_slim'))
)

shape: (0, 18)
┌──────────┬──────────┬──────────┬─────┬───┬─────┬─────┬─────┬─────┐
│ out_nest ┆ out_line ┆ out_slim ┆ a   ┆ … ┆ d5  ┆ d6  ┆ d7  ┆ d8  │
│ ---      ┆ ---      ┆ ---      ┆ --- ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ i32      ┆ i32      ┆ i32      ┆ f64 ┆   ┆ f64 ┆ f64 ┆ f64 ┆ f64 │
╞══════════╪══════════╪══════════╪═════╪═══╪═════╪═════╪═════╪═════╡
└──────────┴──────────┴──────────┴─────┴───┴─────┴─────┴─────┴─────┘

In [7]:
# base case output frequency
df_out.group_by('out_nest').len()

shape: (9, 2)
┌──────────┬────────┐
│ out_nest ┆ len    │
│ ---      ┆ ---    │
│ i32      ┆ u32    │
╞══════════╪════════╡
│ 0        ┆ 500519 │
│ 6        ┆ 62691  │
│ 7        ┆ 62575  │
│ 8        ┆ 62148  │
│ 3        ┆ 62467  │
│ 5        ┆ 62592  │
│ 4        ┆ 62285  │
│ 2        ┆ 62233  │
│ 1        ┆ 62490  │
└──────────┴────────┘

In [8]:
# create different skews
df_skew = (
df_out
.with_columns(threshhold = pl.when(pl.col('out_nest') > 0).then(10 - pl.col('out_nest')).otherwise(5))
.filter( pl.col('out_nest').cum_count().over('out_nest') <= pl.col('threshhold')*7000 )
)

print(df_skew.shape[0])

(
df_skew
.group_by('out_nest')
.len()
.sort('out_nest')
.with_columns( p = pl.col('len') / pl.col('len').sum() )
)

342490
342490

shape: (9, 3)
┌──────────┬───────┬──────────┐
│ out_nest ┆ len   ┆ p        │
│ ---      ┆ ---   ┆ ---      │
│ i32      ┆ u32   ┆ f64      │
╞══════════╪═══════╪══════════╡
│ 0        ┆ 35000 ┆ 0.102193 │
│ 1        ┆ 62490 ┆ 0.182458 │
│ 2        ┆ 56000 ┆ 0.163508 │
│ 3        ┆ 49000 ┆ 0.14307  │
│ 4        ┆ 42000 ┆ 0.122631 │
│ 5        ┆ 35000 ┆ 0.102193 │
│ 6        ┆ 28000 ┆ 0.081754 │
│ 7        ┆ 21000 ┆ 0.061316 │
│ 8        ┆ 14000 ┆ 0.040877 │
└──────────┴───────┴──────────┘

In [9]:
# final prep - standardizing data size
df_skew = pl.concat([df_skew]*4).drop( cs.starts_with('out_') )
df_unif = pl.DataFrame( np.random.rand( df_skew.shape[0],p) )
df_unif.columns = ['a','b1','b2','c1','c2','c3','c4','d1','d2','d3','d4','d5','d6','d7','d8']

In [10]:
### Timing

con = duckdb.connect()
con.sql("SET enable_object_cache = false;")

#### Base Case

In this case all nodes are equally likely

In [11]:
qry_nest = f"select {'+'.join([sql_nest]*100)} as pred from df_unif"
qry_line = f"select {'+'.join([sql_line]*100)} as pred from df_unif"
qry_slim = f"select {'+'.join([sql_slim]*100)} as pred from df_unif"

In [12]:
%%timeit -n 1 -r 50

con.sql(qry_nest).execute()

673 ms ± 31.8 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)
673 ms ± 31.8 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)

In [13]:
%%timeit -n 1 -r 50

con.sql(qry_line).execute()

2.5 s ± 93.1 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)
2.5 s ± 93.1 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)

In [14]:
%%timeit -n 1 -r 50

con.sql(qry_slim).execute()

1.43 s ± 48.5 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)
1.43 s ± 48.5 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)

#### Skewed Case

In this case, nodes are skewed, so we can see benefit from the linearized version ordering by node size

In [15]:
qry_nest = f"select {'+'.join([sql_nest]*100)} as pred from df_skew"
qry_line = f"select {'+'.join([sql_line]*100)} as pred from df_skew"
qry_slim = f"select {'+'.join([sql_slim]*100)} as pred from df_skew"

In [16]:
%%timeit -n 1 -r 50

con.sql(qry_nest).execute()

673 ms ± 39.7 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)
673 ms ± 39.7 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)

In [19]:
%%timeit -n 1 -r 50

con.sql(qry_line).execute()

2.49 s ± 132 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)
2.49 s ± 132 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)

In [18]:
%%timeit -n 1 -r 50

con.sql(qry_slim).execute()

1.45 s ± 57.3 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)
1.45 s ± 57.3 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)